# Generated by Django 5.1.6 on 2025-02-28 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time_create')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Time_update')),
                ('is_published', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Image')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time_create')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Time_update')),
                ('is_published', models.BooleanField(default=True, null=True, verbose_name='Status')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newss', to='news.category')),
            ],
        ),
    ]
