# Generated by Django 5.1.6 on 2025-05-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
