# Generated by Django 5.1.6 on 2025-04-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_product_category_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Ad')),
                ('surname', models.CharField(max_length=300, verbose_name='Soyad')),
                ('age', models.PositiveIntegerField(verbose_name='Yaş')),
                ('birthday', models.DateField(verbose_name='Doğum tarixi')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Yaranma tarixi')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.gender', verbose_name='Cinsi')),
            ],
        ),
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d/', verbose_name='Image')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time_create')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Time_update')),
                ('is_published', models.BooleanField(default=True, null=True, verbose_name='Status')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.developer', verbose_name='Developer')),
            ],
        ),
    ]
