# Generated by Django 5.1.6 on 2025-04-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_developer_about_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='developer',
        ),
    ]
