# Generated by Django 5.1.6 on 2025-04-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_about_us_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='experience',
            field=models.PositiveIntegerField(default=1, verbose_name='Experience (years)'),
        ),
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='developers/'),
        ),
        migrations.AddField(
            model_name='developer',
            name='position',
            field=models.CharField(default='Developer', max_length=300, verbose_name='Position'),
        ),
    ]
